version: '3.9'

services:
  client:
    container_name: gocars-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - ./client/.env
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    networks:
      - gocars-network

networks:
  gocars-network:
    driver: bridge